### ISSUE TITLE
Sieht gar nicht gut aus

### ISSUE THREAD

**Issue by tomo2403** [Skzter/dmx_dt#2]
Versucht es vielleicht erstmal mit Scratch, oder so.

**Comment by Skzter** [comment]
So ein Quatsch. Geh mal lieber deine 1000 Zeilen bearbeiten und babbel mich nicht voll.

**Comment by tomo2403** [comment]
Habt das Ding ja nicht mal kommentiert. Wisst wahrscheinlich selber nicht, was da steht. Das kommt nunmal davon, wenn man nur ChatGPT benutzt. 🤷‍♂️
